# Trial number:      137
# HOTA, MOTA, IDF1:  [55.567]
# Группа 1, получила такие параметры для своей постобработки
# одна ошибка

ocsort:
  asso_func: ct_dist
  det_thresh: 0.22674377174063307
  delta_t: 8
  inertia: 0.44050638675555287
  iou_thresh: 0.4265195613440462
  max_age: 10
  min_hits: 1
  use_byte: False

