# optune accuracy  90.69767441860465
bytetrack:
  track_thresh: 0.4  # tracking confidence threshold
  track_buffer: 50   # the frames for keep lost tracks
  match_thresh: 0.8  # matching threshold for tracking
  frame_rate: 15     # FPS, берем из видео файла
  conf_thres: 0.5
