# optune accuracy  90.69767441860465
bytetrack:
  track_thresh: 0.3  # tracking confidence threshold
  track_buffer: 30   # the frames for keep lost tracks
  match_thresh: 0.9  # matching threshold for tracking
  frame_rate: 15     # FPS, надо брать из видео файла
  conf_thres: 0.9
